# docker-compose up -d
version: '3.7'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.6
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - SPAN_STORAGE_TYPE=postgresql
      - POSTGRES_SERVER_HOST=postgres
      - POSTGRES_SERVER_PORT=5432
      - POSTGRES_DB=jaeger
      - POSTGRES_USER=jaeger
      - POSTGRES_PASSWORD=jaeger
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_DB=jaeger
      - POSTGRES_USER=jaeger
      - POSTGRES_PASSWORD=jaeger
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: